services:
  - type: worker
    name: hypercore-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DEFAULT_WEBHOOK
        sync: false
